apiVersion: v1
kind: Secret
metadata:
  name: pterodactyl-panel
type: Opaque
data:
  database-password: {{ .Values.db.database_password | b64enc | quote }}
  redis-password: {{ .Values.redis.redis_password | b64enc | quote }}